services:
  frontend:
    build: ./solardoc/frontend
    volumes:
      - ./solardoc/frontend:/home/node/app
    ports:
      - "80:80"
    depends_on:
      - rest-api
  rest-api:
    build:
      context: .
      dockerfile: ./solardoc/rest-api/Dockerfile
    volumes:
      - ./solardoc/rest-api:/home/node/app
    ports:
      - "3000:3000"
