services:
  frontend:
    build:
      context: .
      dockerfile: ./solardoc/frontend/Dockerfile
      args:
        VITE_PROD_BACKEND_HOST: http://localhost
        VITE_PROD_BACKEND_PORT: 3000
    volumes:
      - ./solardoc/frontend:/home/node/app
    ports:
      - "80:80"
    depends_on:
      - rest-api
    links:
      - rest-api
  rest-api:
    build: ./solardoc/rest-api
    volumes:
      - ./solardoc/rest-api:/home/node/app
    ports:
      - "3000:3000"
