services:
  frontend:
    build:
      context: .
      dockerfile: ./solardoc/frontend/Dockerfile
      args:
        PUPPETEER_SKIP_DOWNLOAD: "true"
    volumes:
      - ./solardoc/frontend:/home/node/app
      - ./solardoc/frontend/nginx/nginx-dev.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    environment:
      PUPPETEER_SKIP_DOWNLOAD: true
      PROD_BACKEND_PORT: ${PROD_BACKEND_PORT}
      PROD_BACKEND_HOST: ${PROD_BACKEND_HOST}
      API_BASE_PATH: ${API_BASE_PATH}
      NODE_ENV: production
    depends_on:
      - rest-api
    links:
      - rest-api
    restart: always
  rest-api:
    build:
      context: .
      dockerfile: ./solardoc/rest-api/Dockerfile
      args:
        PUPPETEER_SKIP_DOWNLOAD: "true"
        PERSISTENT_STORAGE_PATH: ${PERSISTENT_STORAGE_PATH}
    ports:
      - "3000:3000"
    environment:
      API_BASE_PATH: ${API_BASE_PATH}
      REDIS_ROOT_PASSWORD: ${REDIS_ROOT_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: redis-db
      REDIS_PORT: 6379
      PERSISTENT_STORAGE_PATH: ${PERSISTENT_STORAGE_PATH}
      PUPPETEER_SKIP_DOWNLOAD: "true"
      NODE_ENV: production
    volumes:
      - rest-api-persistent-storage:${PERSISTENT_STORAGE_PATH}
    depends_on:
      redis-db:
        condition: service_healthy
    links:
      - redis-db
    restart: always
  redis-db:
    build: ./solardoc/redis-db
    ports:
      - "6379:6379"
      - "8001:8001"
    privileged: true
    volumes:
      - ./solardoc/redis-db/data:/redis/data
    environment:
      REDIS_ROOT_PASSWORD: ${REDIS_ROOT_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: always

volumes:
  frontend:
  rest-api-persistent-storage:

