services:
  frontend:
    build: ./solardoc/frontend
    volumes:
      - ./solardoc/frontend:/home/node/app
    ports:
      - "80:80"
    depends_on:
      - rest-api
  rest-api:
    build: ./solardoc/rest-api
    volumes:
      - ./solardoc/rest-api:/home/node/app
    ports:
      - "3000:3000"
  redis-db:
    build: ./solardoc/redis-db
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: --requirepass ${REDIS_PASSWORD}
