services:
  frontend:
    build: ./solardoc/frontend
    volumes:
      - ./solardoc/frontend:/home/node/app
    ports:
      - "80:80"
    depends_on:
      - rest-api
  rest-api:
    build:
      context: .
      dockerfile: ./solardoc/rest-api/Dockerfile
    volumes:
      - ./solardoc/rest-api:/home/node/app
    ports:
      - "3000:3000"
  redis-db:
    build: ./solardoc/redis-db
    ports:
      - "6379:6379"
      - "8001:8001"
    privileged: true
    volumes:
      - ./solardoc/redis-db/data:/data
    environment:
      REDIS_ROOT_PASSWORD: ${REDIS_ROOT_PASSWORD}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
